Implemented Restart and Preset change
compujuckel/AssettoServer pull request #70
Opened 2024-01-18 00:54 UTC by thisguyStan

- Implemented internal restart
- Implemented Service for presets
- Added Plugin for track changes

2024-01-21 13:23 UTC, compujuckel requested changes

2024-01-21 14:13 UTC, thisguyStan commented on CyclePresetPlugin/Preset/PresetManager.cs
> +            Thread.Sleep(sleep);
Changed method to async, changed Thread.Sleep to Task.Delay

2024-01-21 14:16 UTC, thisguyStan commented on CyclePresetPlugin/Preset/PresetConfiguration.cs
> +        var cfg = deserializer.Deserialize<CyclePresetConfiguration>(yamlParser).Meta;
Simplified the deserialization 

https://github.com/thisguyStan/AssettoServer/blob/track-change/CyclePresetPlugin/Preset/PresetConfiguration.cs#L39-L41

2024-01-21 14:17 UTC, thisguyStan commented on CyclePresetPlugin/CyclePresetPlugin.cs
> +            VotingAsync(_cancellationToken, true).GetAwaiter().GetResult();
Unblocked the Task

2024-01-21 14:18 UTC, thisguyStan commented on CyclePresetPlugin/CyclePresetCommandModule.cs
> +        _cyclePreset.ListAllPresets(Client!);
Updated all Commands to use `BaseCommandContext` instead of `ACTcpClient`

2024-01-23 20:44 UTC, merged

2024-01-23 20:44 UTC, compujuckel commented
Thanks!